### ISSUE TITLE
Deployment confusion

### ISSUE THREAD

**Issue by jacktilford** [jcoliz/yofi#1]
I wanted to try out your interesting app; I followed instructions for deploying to Azure. I ended up with an apparently read-only database containing the sample data instead of an empty database. What did I do wrong?

**Comment by jcoliz** [comment]
Hi there. Thanks for trying it out! I will look at this in the next couple days to see if I can reproduce it. What method did you use to deploy? The "deploy to azure" button?

It would be helpful if you could post a screenshot of the deployment results from the portal. Or send privately jcoliz@outlook.com.

Sorry for delay in responding, I wasn't expecting  any attention yet  :)

**Comment by jcoliz** [comment]
@jacktilford Hi, thanks again for trying it out. I just now did this with a fresh deployment, and everything seemed fine. Typically in cases like this, it means I assume something and didn't communicate it.

For starters, it's by design that the database is seeded with test data. The idea is that a user evaluating the system can have a richer experience if there's something there for them to try. However, there's not a super simple path to remove the sample data or deploy without it. What you'd have to do is (1) set an environment variable "BRAND__NAME" to something, e.g. "jacktilford", AND (2) log into the sql server using the generated password (still available in the 'inputs' page for your deployment), and delete all the data. There is a script at Yofi.AspNet/Data/DeleteAllData.sql which I use for this. I recognize that this is not ideal and should be improved.

What is the symptom of "apparently read-only database"? Did you get the red banner saying "WARNING Demonstration use only. Do not enter any real data!", like at www.try-yofi.com? Did you try deleting a transaction?

Also, questions from my earlier reply still apply... How deploy, and it would be great to see a screenshot of your deployment comparable to this one: https://github.com/jcoliz/yofi/blob/master/docs/images/postdeploy-1.png

**Comment by jacktilford** [comment]
Hi James,

Thanks for the replies. I've got to run right now (will reply in more detail later), but your answers clear things up. I assumed it was readonly because I didn't see any way to delete transactions in the UI, and I couldn't get Import to work.

Jack

**Comment by jcoliz** [comment]
Thanks, @jacktilford. Your deployment is probably fine then. 

I need to work on the user experience for someone who deploys to Azure. I think I will make the process of adding sample data be a choice given to the user on first run. This will have the side benefit of improving the speed of load on first run (which is quite long right now). 

* Added [User Story 1265](https://dev.azure.com/jcoliz/YoFi/_workitems/edit/1265): [User Can] Decide whether or not to populate database with sample data on first run

What did you try to import? I have plans to give users sample files to upload on the Upload page, this might help.

* Added [User Story 1266](https://dev.azure.com/jcoliz/YoFi/_workitems/edit/1266): [User Can] Download sample OFX & XLSX files while on the import page

Deleting transactions is intentionally buried. I found that I very rarely do this. So you'd press the "edit" icon next to a transaction, then "more" on that dialog, then there is a delete button on the subsequent edit page.

**Comment by jcoliz** [comment]
Hey, @jacktilford. Wanted to let you know that I just released version 0.9.7 which makes the changes described in my last comment. If you want to give it another try in a fresh deployment, I'd love to hear how it goes for you.
